dropwizard:
  image: java:8-jre
  ports:
   - "8090:8090"
  volumes:
   - volume-dropwizard:/dropwizard
  command: ["java", "-jar", "-Done-jar.silent=true", "/dropwizard/dropwizard-application.jar", "server", "/dropwizard/config.yml"]

web:
  image: nginx
  links:
   - dropwizard
  ports:
   - "8080:80"
  volumes:
   - volume-nginx-conf.d:/etc/nginx/conf.d
   - volume-nginx-log:/var/log/nginx

client:
  image: buildpack-deps:sid-curl
  links:
   - web
  command: 'curl http://web:80/hello'
